# Site settings
title: The Gooberati
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In which we describe our travels in Italy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
